name: Build and deploy

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2

    - name: npm install
      run: npm install && npm install -g @angular/cli

    - name: Build app
      run: ng build --prod

    - name: Create inventory file
      if: github.ref == 'refs/heads/master'
      run: echo ${{ secrets.INSTANCE_IP }} > ./deployment/hosts

    - name: Execute Ansible Playbook
      if: github.ref == 'refs/heads/master'
      uses: arillso/action.playbook@0.0.2
      with:
       playbook: ./deployment/deploy.yaml
       inventory: ./deployment/hosts
       private_key: ${{ secrets.SSH_KEY }}
       user: deployer
      env:
        ANSIBLE_HOST_KEY_CHECKING: 'false'
        ANSIBLE_DEPRECATION_WARNINGS: 'false'
